# Generated by Django 3.1 on 2020-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan_offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField(max_length=300)),
                ('employee_id', models.IntegerField()),
                ('date_of_entry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SignupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('contact_no', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('last_qualification', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('id_proof_no', models.IntegerField()),
                ('id_proof_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], default='Manager', max_length=20)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('date_of_birth', models.DateField(max_length=100)),
                ('date_of_registration', models.DateField(max_length=100)),
                ('time_of_registration', models.TimeField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Signup Data',
            },
        ),
    ]
