# Generated by Django 3.1.1 on 2020-10-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewLoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='id_proof_no',
            field=models.BigIntegerField(),
        ),
    ]
